create table identitaspasien (

	id INT PRIMARY KEY AUTO_INCREMENT,
	noRM VARCHAR(255) NOT NULL,
	nmPasien VARCHAR(255) NOT NULL,
	tmpLahir VARCHAR(255) NOT NULL,
	tglLahir DATE NOT NULL,
	jk VARCHAR(255) NOT NULL,
	goldar VARCHAR(255) NOT NULL,
	usia VARCHAR(255) NOT NULL,
	noKTP VARCHAR(255) NOT NULL,
	alamat VARCHAR(255) NOT NULL,
	pekerjaan VARCHAR(255) NOT NULL,
	sttsNikah VARCHAR(255) NOT NULL,
	agama VARCHAR(255) NOT NULL, 
	noTelp VARCHAR(255) NOT NULL,
	keluarga VARCHAR(255) NOT NULL,
	nmkeluarga VARCHAR(255) NOT NULL,
	pnd VARCHAR(255) NOT NULL
) Engine=InnoDB;